module.exports = {
  plugins: ['jest'],
  rules: {
    'jest/consistent-test-it': 2,
    'jest/expect-expect': 2, // TODO: 一旦入れて様子見
    'jest/lowercase-name': 0,
    'jest/max-nested-describe': 0,
    'jest/no-alias-methods': 2,
    'jest/no-commented-out-tests': 0,
    'jest/no-conditional-expect': 0,
    'jest/no-conditional-in-test': 0,
    'jest/no-deprecated-functions': 0,
    'jest/no-disabled-tests': 1,
    'jest/no-done-callback': 0,
    'jest/no-duplicate-hooks': 2,
    'jest/no-export': 0,
    'jest/no-focused-tests': 2,
    'jest/no-hooks': 0,
    'jest/no-identical-title': 2,
    'jest/no-if': 2,
    'jest/no-interpolation-in-snapshots': 0,
    'jest/no-jasmine-globals': 2,
    'jest/no-jest-import': 2,
    'jest/no-large-snapshots': 0,
    'jest/no-mocks-import': 0,
    'jest/no-restricted-matchers': 0,
    'jest/no-standalone-expect': 0,
    'jest/no-test-prefixes': 2,
    'jest/no-test-return-statement': 2,
    'jest/prefer-called-with': 2,
    'jest/prefer-comparison-matcher': 0,
    'jest/prefer-equality-matcher': 0,
    'jest/prefer-expect-assertions': 0,
    'jest/prefer-expect-resolves': 0,
    'jest/prefer-hooks-on-top': 0,
    'jest/prefer-lowercase-title': 2,
    'jest/prefer-snapshot-hint': 2,
    'jest/prefer-spy-on': 2,
    'jest/prefer-strict-equal': 2,
    'jest/prefer-to-be': 0,
    'jest/prefer-to-be-null': 0,
    'jest/prefer-to-be-undefined': 0,
    'jest/prefer-to-contain': 2,
    'jest/prefer-to-have-length': 2,
    'jest/prefer-todo': 0,
    'jest/require-hook': 0,
    'jest/require-to-throw-message': 2,
    'jest/require-top-level-describe': 0,
    'jest/unbound-method': 0,
    'jest/valid-describe-callback': 0,
    'jest/valid-expect': 2,
    'jest/valid-expect-in-promise': 0,
    'jest/valid-title': 0,
  },
  env: {
    'jest/globals': true,
  },
}
